
#pragma once

#include <QColor>

#include "types.h"

#define _FLUID_DEFAULT_SOUNDFONT_FILE "/home/pi/AdjRaspiSynth5qtApp_2/SoundFonts/FluidR3_GM.sf2"
#define _FLUID_DEFAULT_SOUNDFONT_DIR "/home/pi/AdjRaspiSynth5qtApp_2/SoundFonts"

#define _FLUID_PRESETS_FILES_DEFAULT_DIR "/home/pi/AdjRaspiSynth5qtApp_2/Presets/Fluid"

#define _PATCHES_FILES_DEFAULT_DIR "/home/pi/AdjRaspiSynth5qtApp_2/Patches"

#define _MIDI_PLAYBACK_FILES_DEFAULT_DIR "/home/pi/AdjRaspiSynth5qtApp_2/MidiFiles/Playback"

#define _HAMMOND_ORGAN_PRESETS_FILES_DEFAULT_DIR "/home/pi/AdjRaspiSynth5qtApp_2/Presets/HammondOrgan"
#define _STRING_SYNTH_PRESETS_FILES_DEFAULT_DIR "/home/pi/AdjRaspiSynth5qtApp_2/Presets/StringSynth"
#define _PAD_SYNTH_PRESETS_FILES_DEFAULT_DIR "/home/pi/AdjRaspiSynth5qtApp_2/Presets/PADsynth"
#define _MSO_SYNTH_PRESETS_FILES_DEFAULT_DIR "/home/pi/AdjRaspiSynth5qtApp_2/Presets/MSOsynth"

#define _RECORDINGS_MP3_FILES_DEFAULT_DIR "/home/pi/AdjRaspiSynth5qtApp_2/Recordings"


#define _MIDI_MIXER_CHANNELS_1_8	0
#define _MIDI_MIXER_CHANNELS_9_16	1

#define _OSC_1_TAB					0
#define _OSC_2_TAB					1
#define _NOISE_TAB					2
#define _MSO_TAB					3
#define _KARPLUS_TAB				4
#define _PAD_SYNTH_TAB				5
#define _FILTERS_AMPS_TAB			6
#define _MODULATORS_ADSRS_TAB		7
#define _MODULATORS_LFOS_TAB		8
#define _DISTORTION_TAB				9

#define _ANALOG_SOURCES_TAB			100
#define _ANALOG_PROCESSING_TAB		101

#define _FRAMES_GROUP_1				0
#define _FRAMES_GROUP_2				1
#define _FRAMES_GROUP_3				2

#define _CONTROL_COLOR_BLACK		QColor(110, 110, 110)
#define _CONTROL_COLOR_GREEN		QColor(22, 205, 75)
#define _CONTROL_COLOR_RED			QColor(255, 0, 0)
#define _CONTROL_COLOR_BLUE			QColor(10, 149, 255)
#define _CONTROL_COLOR_WHITE		QColor(255, 255, 255)
#define _CONTROL_COLOR_YELLOW		QColor(255, 255, 0)

#define _BACKGROUND_COLOR_CYAN		"background-color: rgb(0, 255, 255);"
#define _BACKGROUND_COLOR_ORANGE	"background-color: rgb(255, 85, 0);"
#define _BACKGROUND_COLOR_GRAY		"background-color: rgb(230, 230, 230);"

#define _BACKGROUND_PANEL_COLOR_GRAY		"background-color: rgb(200, 200, 220);"
#define _BACKGROUND_PANEL_COLOR_DARK_GRAY	"background-color: rgb(100, 100, 120);"
#define _BACKGROUND_PANEL_COLOR_WHITE		"background-color: rgb(240, 240, 240);"

#define _INSTRUMENT_PANNEL_FRAME_COLOR_PLAYER QColor(50, 90, 230) // Blue
#define _INSTRUMENT_PANNEL_FRAME_COLOR_EFFECT QColor(0, 255, 255) // Cyan
#define _INSTRUMENT_PANNEL_FRAME_COLOR_CONTROL QColor(245, 65, 20) // Red

#define _SEND_FILTER_MAX			100
#define _SEND_FILTER_MIN			0

#define _MODULATION_LEVEL_MAX		100
#define _MODULATION_LEVEL_MIN		0

#define _OSC_WAVEFORM_SYMETRY_MAX	95
#define _OSC_WAVEFORM_SYMETRY_MIN	5

#define _OSC1_UNISON_LEVEL_MAX		100
#define _OSC1_UNISON_LEVEL_MIN		0
#define _OSC1_UNISON_DETUNE_MAX		100
#define _OSC1_UNISON_DETUNE_MIN		0
#define _OSC1_UNISON_DISTORTION_MAX	100
#define _OSC1_UNISON_DISTORTION_MIN	0

#define _KPS_MAX_SLIDER_VALUE		100
#define _KPS_MIN_SLIDER_VALUE		1

#define _PAD_MAX_SLIDER_VALUE		100
#define _PAD_MIN_SLIDER_VALUE		0

#define _FILTER_KNOB_MAX_VALUE		100
#define _FILTER_KNOB_MIN_VALUE		0

#define _AMP_KNOB_MAX_VALUE			100
#define _AMP_KNOB_MIN_VALUE			0

#define _MSO_PRESET_USER			0
#define _MSO_PRESET_SINE			1
#define _MSO_PRESET_SQUARE			2
#define _MSO_PRESET_PULSE			3
#define _MSO_PRESET_SAW				4

#define _LFO_RATE_ENTRY_MAX			100
#define _LFO_RATE_ENTRY_MIN			0
#define _LFO_SYMMETRY_ENTRY_MAX		95
#define _LFO_SYMMETRY_ENTRY_MIN		5

#define _ADSR_SLIDER_VALUE_MAX		100
#define _ADSR_SLIDER_VALUE_MIN		0

#define _DISTORTION_ENTRY_MAX		100
#define _DISTORTION_ENTRY_MIN		0

#define _ADSR_CURVE_START_POINT					0
#define _ADSR_CURVE_TIME_MULTIPLIER				8		// 8 pixels per second
#define _ADSR_CURVE_SUSTAIN_SEGMENT_LENGTH		40
#define _ADSR_CURVE_HEIGHT						90

#define _MSO_SYNTH_ADSR_CURVE_START_POINT 0
#define _MSO_SYNTH_ADSR_CURVE_TIME_MULTIPLIER 8 // 8 pixels per second
#define _MSO_SYNTH_ADSR_CURVE_SUSTAIN_SEGMENT_LENGTH 40
#define _MSO_SYNTH_ADSR_CURVE_HEIGHT 55

#define _ADSR_CURVE_VIEW_WIDGET_SHOW_TIME_SEC	5

#define _MAX_NUM_OF_INSTRUMENTS					128

/************ New APP 2 Starts here *******************/

// Knobs and Sliders Caps Colors
#define _CONTROLS_COLOR_DARK_GRAY		QColor(70, 70, 70)
#define _CONTROLS_COLOR_VERY_DARK_GRAY	QColor(30, 30, 30)
#define _CONTROLS_COLOR_GRAY			QColor(150, 150, 150)
#define _CONTROLS_COLOR_LIGHT_GRAY		QColor(100, 100, 100)
#define _CONTROLS_COLOR_GREEN		QColor(110, 240, 60)
#define _CONTROLS_COLOR_BLUE		QColor(60, 126, 240)
#define _CONTROLS_COLOR_WHITE		QColor(255, 255, 255, 255)
#define _CONTROLS_COLOR_PURPLE		QColor(170, 85, 255)
#define _CONTROLS_COLOR_RED			QColor(240, 90, 90)
#define _CONTROLS_COLOR_YELLOW		QColor(255, 255, 0)
#define _CONTROLS_COLOR_BLACK		QColor(15, 15, 15)

#define _KNOBS_COLOR				_CONTROLS_COLOR_GRAY

#define _SLIDERS_TRACK_COLOR		_CONTROLS_COLOR_LIGHT_GRAY
#define _SLIDERS_BACKGROUND_COLOR	_CONTROLS_COLOR_DARK_GRAY

#define _GUI_BACKGROUND_COLOR		QColor(5, 5, 5)

#define _CONTROL_GROUP_GRAY			_CONTROLS_COLOR_LIGHT_GRAY
#define _CONTROL_GROUP_WHITE		_CONTROLS_COLOR_WHITE
#define _CONTROL_GROUP_NOT_SELECTED QColor(40, 40, 40)

#define _KNOB_COLOR_INDEX						0
#define _KNOB_CIRCLE_COLOR_INDEX				1

#define _COMBOBOX_BACKGROUND_COLOR_INDEX		0
#define _COMBOBOX_FRAME_COLOR_INDEX				1

#define _HORIZONTAL_SLIDER_FRAME_COLOR_INDEX	0
#define _HORIZONTAL_SLIDER_PROGRESS_COLOR_INDEX	1
#define _HORIZONTAL_SLIDER_HANDLE_COLOR_INDEX	2


#define _VERTICAL_SLIDER_FRAME_COLOR_INDEX		0
#define _VERTICAL_SLIDER_PROGRESS_COLOR_INDEX	1
#define _VERTICAL_SLIDER_HANDLE_COLOR_INDEX		2

#define _BUTTON_BACKGROUND_COLOR_INDEX 0
#define _BUTTON_TEXT_COLOR_INDEX 1
#define _BUTTON_FRAME_COLOR_INDEX 2

#define _OSC1_FREQ_MOD_ADSR_COMBOBOX_INDEX		0
#define _OSC1_PWM_MOD_ADSR_COMBOBOX_INDEX		1
#define _OSC1_AMP_MOD_ADSR_COMBOBOX_INDEX		2

#define _OSC2_FREQ_MOD_ADSR_COMBOBOX_INDEX		3
#define _OSC2_PWM_MOD_ADSR_COMBOBOX_INDEX		4
#define _OSC2_AMP_MOD_ADSR_COMBOBOX_INDEX		5

#define _MSO_FREQ_MOD_ADSR_COMBOBOX_INDEX		6
#define _MSO_PWM_MOD_ADSR_COMBOBOX_INDEX		7
#define _MSO_AMP_MOD_ADSR_COMBOBOX_INDEX		8

#define _PAD_FREQ_MOD_ADSR_COMBOBOX_INDEX		9
#define _PAD_AMP_MOD_ADSR_COMBOBOX_INDEX		10

#define _NOISE_AMP_MOD_ADSR_COMBOBOX_INDEX		11

#define _FILTER1_FREQ_MOD_ADSR_COMBOBOX_INDEX	12
#define _FILTER2_FREQ_MOD_ADSR_COMBOBOX_INDEX	13

#define _OSC1_FREQ_MOD_LFO_COMBOBOX_INDEX		20
#define _OSC1_PWM_MOD_LFO_COMBOBOX_INDEX		21
#define _OSC1_AMP_MOD_LFO_COMBOBOX_INDEX		22

#define _OSC2_FREQ_MOD_LFO_COMBOBOX_INDEX		23
#define _OSC2_PWM_MOD_LFO_COMBOBOX_INDEX		24
#define _OSC2_AMP_MOD_LFO_COMBOBOX_INDEX		25

#define _MSO_FREQ_MOD_LFO_COMBOBOX_INDEX		26
#define _MSO_PWM_MOD_LFO_COMBOBOX_INDEX			27
#define _MSO_AMP_MOD_LFO_COMBOBOX_INDEX			28

#define _PAD_FREQ_MOD_LFO_COMBOBOX_INDEX		29
#define _PAD_AMP_MOD_LFO_COMBOBOX_INDEX			30

#define _NOISE_AMP_MOD_LFO_COMBOBOX_INDEX		31

#define _FILTER1_FREQ_MOD_LFO_COMBOBOX_INDEX	32
#define _FILTER2_FREQ_MOD_LFO_COMBOBOX_INDEX	33

#define _AMP1_PAN_MOD_LFO_COMBOBOX_INDEX		34
#define _AMP2_PAN_MOD_LFO_COMBOBOX_INDEX		35

#define _MIXER_CHAN1_PAN_MOD_LFO_COMBOBOX_INDEX 36
#define _MIXER_CHAN2_PAN_MOD_LFO_COMBOBOX_INDEX 37
#define _MIXER_CHAN3_PAN_MOD_LFO_COMBOBOX_INDEX 38
#define _MIXER_CHAN4_PAN_MOD_LFO_COMBOBOX_INDEX 39
#define _MIXER_CHAN5_PAN_MOD_LFO_COMBOBOX_INDEX 40
#define _MIXER_CHAN6_PAN_MOD_LFO_COMBOBOX_INDEX 41
#define _MIXER_CHAN7_PAN_MOD_LFO_COMBOBOX_INDEX 42
#define _MIXER_CHAN8_PAN_MOD_LFO_COMBOBOX_INDEX 43
#define _MIXER_CHAN9_PAN_MOD_LFO_COMBOBOX_INDEX 44
#define _MIXER_CHAN10_PAN_MOD_LFO_COMBOBOX_INDEX 45
#define _MIXER_CHAN11_PAN_MOD_LFO_COMBOBOX_INDEX 46
#define _MIXER_CHAN12_PAN_MOD_LFO_COMBOBOX_INDEX 47
#define _MIXER_CHAN13_PAN_MOD_LFO_COMBOBOX_INDEX 48
#define _MIXER_CHAN14_PAN_MOD_LFO_COMBOBOX_INDEX 49
#define _MIXER_CHAN15_PAN_MOD_LFO_COMBOBOX_INDEX 50
#define _MIXER_CHAN16_PAN_MOD_LFO_COMBOBOX_INDEX 51

#define _MODULATOR_FRAME_NO_ACTIVITY_TIMOUT_COUNT	50 // 50 x 100ms = 5 seconds _UPDATE_TIMER_PERIOD_MS

class InstrumentPannel;

typedef struct activeInstruments
{
	en_instruments_ids_t instrument_id;
	QString instrument_name;
	InstrumentPannel *instrument_pannel_object;
	bool pending_close_event;
	
	activeInstruments(en_instruments_ids_t instrument_id = en_instruments_ids_t::none_instrument_id)
		: instrument_id(instrument_id)
	{}
	
	
} active_instrument_data_t;



